name: Deploy dApp to Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deployment with SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: deployer
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo -e "\033[0;32mDeploying to production server...\033[0m"

            cd ~/apps/dapp
            source ~/.bashrc
            export PATH="$HOME/.nvm/versions/node/v22.17.0/bin:$PATH"
            export PATH="$HOME/.local/share/pnpm:$PATH"

            git reset --hard HEAD
            git clean -fd
            git pull origin main

            pnpm install
            pnpm run build
            pm2 restart dapp || pm2 start .output/server/index.mjs --name dapp

            echo -e "\033[0;32mDeployment completed successfully!\033[0m"
